Updated OAuth2 implementation
Team-Challenge-Game-Shop/backend pull request #2
Opened 2024-09-12 15:57 UTC by EconLQ

removed GoogleTokenInfo and proceeded with the token validation process using GoogleIdTokenVerifier

2024-09-12 17:28 UTC, IhorKulishenko commented
There is a little trap in method  `authenticateGoogle`  in particular in line 
`User user = (User) userService.userDetailsService().loadUserByUsername(tokenInfo.getEmail());`
if there there is no user with such email method `loadUserByUsername` doesn't return null but throws an exception, so instead of add new user to local db backend just returns message that user with email not found

2024-09-12 17:35 UTC, IhorKulishenko requested changes

2024-09-12 17:35 UTC, IhorKulishenko commented on src/main/java/com/gameshop/ecommerce/security/auth/service/AuthenticationService.java
> +                User user = (User) userService.userDetailsService().loadUserByUsername(payload.getEmail());
loadUserByUsername throws an exception if there is no user with the email in local db

2024-09-13 08:39 UTC, EconLQ commented
intercepted exception in another method and returned empty optional:

```java
    private Optional<User> getLoadedUserByUsername(String email) {
        User user = null;
        try {
            user = (User) userService.userDetailsService().loadUserByUsername(email);
        } catch (UsernameNotFoundException e) {
            log.warn("User with email {} not found", email);
            return Optional.empty();
        }
        return Optional.of(user);
    }
```

updated logic inside the method `getUserFromGoogleIdToken(String token)`:

```java
              final var payload = googleIdToken.getPayload();
              // check if user with this email already exists
              Optional<User> user = getLoadedUserByUsername(payload.getEmail());
              if (user.isPresent()) {
                  return user;
              }
```

2024-09-13 09:48 UTC, IhorKulishenko requested changes
Pleas look at this updated logic and tell what you think, also I do some refactoring.

2024-09-13 10:10 UTC, EconLQ reviewed
I like the idea of implementing the UserDetailsService interface and overriding the loadUserByUsername method. The only suggestion is to add a log.warn() if `googleIdToken == null`, but that's a minor thing.

2024-09-13 11:28 UTC, merged